---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: service-aa
  namespace: service-aa
spec:
  interval: 2m0s
  url: https://github.com/vincedesjardins/service-a
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: service-aa
  namespace: service-aa
spec:
  interval: 2m
  retryInterval: 30s
  timeout: 5m
  path: ./
  prune: true
  serviceAccountName: fluxcd
  sourceRef:
    kind: GitRepository
    name: service-aa
